teleportPoints:
  - world: world
    x: 2
    y: -33
    z: 607
  - world: world
    x: -114
    y: -27
    z: 607
  - world: world
    x: -122
    y: -28
    z: 703
  - world: world
    x: 24
    y: -30
    z: 708
  - world: world
    x: -10
    y: -29
    z: 456
  - world: world
    x: -162
    y: -28
    z: 465

regions:
  watermelon:
    job: WATERMELON
    min:
      world: world
      x: 53
      y: -53
      z: 31
    max:
      world: world
      x: 84
      y: -31
      z: 0
    chest:
      world: world
      x: 72
      y: -50
      z: 22

  flower:
    job: FLOWER
    min:
      world: world
      x: 53
      y: -54
      z: 55
    max:
      world: world
      x: 84
      y: -19
      z: 86
    chest:
      world: world
      x: 78
      y: -50
      z: 65

  turtle:
    job: TURTLE
    min:
      world: world
      x: 119
      y: -54
      z: 55
    max:
      world: world
      x: 149
      y: -30
      z: 185
    chest:
      world: world
      x: 140
      y: -50
      z: 63

  fishing:
    job: FISHING
    min:
      world: world
      x: 86
      y: -54
      z: 31
    max:
      world: world
      x: 113
      y: -29
      z: -1
    chest:
      world: world
      x: 113
      y: -48
      z: 7

  wood:
    job: WOOD
    min:
      world: world
      x: 119
      y: -53
      z: 31
    max:
      world: world
      x: 148
      y: -29
      z: 2
    chest:
      world: world
      x: 132
      y: -50
      z: 19

  mineral:
    job: MINERAL
    min:
      world: world
      x: 86
      y: -53
      z: 54
    max:
      world: world
      x: 117
      y: -31
      z: 86
    chest:
      world: world
      x: 109
      y: -50
      z: 63

# 스킨 로드 설정
skin-loading:
  enable-mojang-api: true
  enable-profile-api: true
  timeout: 5000

hidden: # 0.01 -> 1%
  watermelon:
    chance: 0.01
    owner: "Garam_0_"
  mineral:
    chance: 0.01
    owner: "kamen9981"
  wood:
    chance: 0.02
    owner: "_DisL_"
  flower:
    chance: 0.01
    owner: "MongGle_5_"
  turtle:
    chance: 0.05
    owner: "JP00000000"
  fishing: 
    chance: 0.03
    owner: "asdf"